
server:
  port: 8806

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/
spring:
  application:
    name: login-consumer
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    password: 
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
ribbon:
  eureka:
    enabled: true