server:
  port: 8805

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/

spring:
  datasource:
    url: jdbc:mysql://106.12.192.14/test?serverTimezone=GMT%2B8
    username: root
    password: 19970121
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: login-production
  redis:
    host: localhost
    port: 6379
    timeout: 0
    password: 
    #过期时间    
    expire: 18000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1