spring:
  datasource:
    url: jdbc:mysql://106.12.192.14/test?serverTimezone=GMT%2B8
    username: root
    password: 19970121
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: test-production
server:
  port: 8802
  tomcat:
   uri-encoding: UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/
mybatis:
  type-aliases-package: com/example/production/pojo
  mapper-locations: classpath:mapper/*xml
